### ISSUE TITLE
Add keys in different file

### ISSUE THREAD

**Issue by bwayne2015** [windlessStorm/allspeak#1]
1.Add google API keys in different files 
2.Use something similar py2exe to provide exe application which will install the dependencies

**Comment by windlessStorm** [comment]
By mistake committed API keys. Have removed it in latest commit. It is still accessible to anyone in from commit history though, have to find out how to remove it from history.

**Comment by windlessStorm** [comment]
Hopefully, no one has forked or cloned the repo. Have removed the sensitive data file from repo history.

[How to remove sensitive data from git history](https://help.github.com/articles/removing-sensitive-data-from-a-repository/)
